### ISSUE TITLE
Data analysis such as regression analysis of the data

### ISSUE THREAD

**Issue by Romeehoeks** [Romeehoeks/Airbnb_project#10]

**Comment by Marijekok** [comment]
Did the first steps. 3 regressions are finished. We only need to find out how to handle with 'attractiveness'.

**Comment by Marijekok** [comment]
structure is included

**Comment by Romeehoeks** [comment]
I think it looks good, lets ask for feedback to see how we indeed can handle with the attractiveness part

**Comment by Romeehoeks** [comment]
completely changed it, but now done
