### ISSUE TITLE
- about section aanpassen (te lang)

### ISSUE THREAD

**Issue by Romeehoeks** [Romeehoeks/Airbnb_project#17]

**Comment by Thomas-H1999** [comment]
@Romeehoeks 
![FhyeE](https://user-images.githubusercontent.com/98875680/158362268-cb45fd73-e727-4cb6-adc3-5fa1c9f06fd2.png)
Found this on the internet however, I dont see the settings icon. Maybe the owner of the repocitory is the only one who can edit the about section?

**Comment by Romeehoeks** [comment]
Okay, I will try this later

**Comment by Romeehoeks** [comment]
Done
