### ISSUE TITLE
Create research question

### ISSUE THREAD

**Issue by Thomas-H1999** [Romeehoeks/Airbnb_project#3]
Lets create a research question, together!

**Comment by HJKlijsen** [comment]
To what extent is the number of listings (one listing vs. multiple listings) affecting the reviews of Airbnb in the Netherlands?

**Comment by MaxvanderMeulen** [comment]
To what extent is renting out your private room on Airbnb worth it based on income, ratings and coverage?

**Comment by Romeehoeks** [comment]
In which city in Europe is the most attractive to rent out your private room?

**Comment by Marijekok** [comment]
To what extent is renting out your private room on Airbnb attractive in terms of income, ratings and coverage? Comparison between different cities in Europe

**Comment by Romeehoeks** [comment]
To what extent is renting out your private room on Airbnb in Europe attractive in terms of income, ratings and coverage?

**Comment by Romeehoeks** [comment]
To what extent is renting out your privare room on Airbnb attractive in Europe term of income, ratings and coverage and which of those cities in Europe is the most attractive?

**Comment by MaxvanderMeulen** [comment]
What is the income, ratings and coverage when renting out your private room in Europe on Airbnb? And which cities in Europa are most attractive?

**Comment by Marijekok** [comment]
In which European city is renting out your private room on Airbnb most attractive in terms of income, ratings and coverage?
