### ISSUE TITLE
Find out if it is allowed to rent your room on Airbnb

### ISSUE THREAD

**Issue by Romeehoeks** [Romeehoeks/Airbnb_project#4]
[](https://www.kamer.nl/blog/studentenkamer-op-airbnb-regels/#:~:text=Hoeveel%20dagen%20mag%20je%20je,niet%20meer%20dan%20vier%20personen)

**Comment by HJKlijsen** [comment]
niks

**Comment by Marijekok** [comment]
hello

**Comment by Marijekok** [comment]
https://www.kamer.nl/blog/studentenkamer-op-airbnb-regels/#:~:text=Hoeveel%20dagen%20mag%20je%20je,niet%20meer%20dan%20vier%20personen.
