### ISSUE TITLE
Research regarding motivation concerning the underlying thoughts

### ISSUE THREAD

**Issue by Romeehoeks** [Romeehoeks/Airbnb_project#6]
Top 10 beste studentensteden

https://www.topuniversities.com/city-rankings/2015#sorting=rank+custom=rank+order=desc+search=

**Comment by Romeehoeks** [comment]
@Marijekok @HJKlijsen @Thomas-H1999 @FikkieUvT Focusen op deze steden? (Indien ze beschikbaar zijn)

**Comment by MaxvanderMeulen** [comment]
Ik denk dat we misschien binnen europa moeten blijven (of amerika) Anders gaan we ook de currencies veranderen.. (ik heb zojuist gecontroleerd en de currenties staan allemaal in $ maar zijn niet omgezet. in Tokyo kost een kamer bijv $4000 per nacht. Maar dat klopt natuurlijk niet. dat is 4000 is japanse currency)

**Comment by Romeehoeks** [comment]
Oh ik had gefilterd op Europa, maar dat kun je niet zien denk ik?

**Comment by MaxvanderMeulen** [comment]
AHHH. Oke nee dat was innd niet via de link. Maar dan is het opgelost! :D
