### ISSUE TITLE
Conceptual_model

### ISSUE THREAD

**Issue by MaxvanderMeulen** [Romeehoeks/Airbnb_project#7]
![airbnb_model](https://user-images.githubusercontent.com/98962990/154692120-d84f802a-d1d1-4385-b258-cc6559c7b36d.png)

**Comment by Romeehoeks** [comment]
This option can be deleted right? Also in the read me structure. I think it is better to go with option 2? If everyone agrees I will delete it in readme structure  @FikkieUvT @Marijekok @HJKlijsen @Thomas-H1999

**Comment by Thomas-H1999** [comment]
Yes this one can be deleted. @Romeehoeks
