### ISSUE TITLE
Work on Rmarkdown

### ISSUE THREAD

**Issue by Romeehoeks** [Romeehoeks/Airbnb_project#8]
2.1 Data exploration (10%)

All raw data files are programmatically downloaded from the internet. Meaningful RMarkdown reports for (types of) raw data/input files are created, which allow potential users of your repository to understand the content of such files, and the definition of variables. The RMarkdown reports are properly formatted, rendered as HTML or PDF files, and feature information in a variety of modes (e.g., running text, tables, or figures). The rendered Markdown files are “publication-ready” - i.e., code that is not relevant to understanding the data or warning messages is hidden.

**Comment by Marijekok** [comment]
Finished. (ps, we work further in github, because if we make changes, we need to adapt it in Rmarkdown again. So first make sure that our project is finished in Github before making it in Rmarkdown.)

**Comment by Romeehoeks** [comment]
Done, 2 markdown files created
