### ISSUE TITLE
Create pipelines in R

### ISSUE THREAD

**Issue by Romeehoeks** [Romeehoeks/Airbnb_project#9]

**Comment by Thomas-H1999** [comment]
Working on this

**Comment by Thomas-H1999** [comment]
created pipelines in Github, but didn't automize them.

**Comment by Romeehoeks** [comment]
@Thomas-H1999 could you do this as well for the anaylsis part? Please write down the steps, so in which order it should run

**Comment by Romeehoeks** [comment]
didn't mean to close it
